// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLv2GeluBwDFUsp6TEi1UZ2IvEOuHCWGY',
    appId: '1:835086418788:android:3d3faef702ae1a90147071',
    messagingSenderId: '835086418788',
    projectId: 'skill-swap-marketplace-6e668',
    storageBucket: 'skill-swap-marketplace-6e668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKZgbSsSW3eXF62U-PDgx1JZBSEKzlT0',
    appId: '1:835086418788:ios:22778a46a0b02c4f147071',
    messagingSenderId: '835086418788',
    projectId: 'skill-swap-marketplace-6e668',
    storageBucket: 'skill-swap-marketplace-6e668.firebasestorage.app',
    iosClientId: '835086418788-g27sj9irrn3h5ru25k305t7pc8t4l9k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillSwapMarketplace',
  );
}
